services:
  backend:
    build:
      context: ../backend
      target: development
    volumes:
      - ../backend:/app
      - sqlite-data:/app/data
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=sqlite:////app/data/demo.db
    command: >
      bash -c "
        mkdir -p /app/data &&
        chown -R vscode:vscode /app/data &&
        chmod 777 /app/data &&
        cd /app &&
        tail -f /dev/null
      "
    tty: true
    stdin_open: true
    labels:
      - "com.demo.app=ai-ready-demo"
      - "com.demo.component=backend"
      - "com.demo.managed-by=start-script"

  frontend:
    build:
      context: ../frontend
      target: development
    volumes:
      - ../frontend:/app
      - frontend-node-modules:/app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8001
    command: npm run dev -- --host 0.0.0.0
    labels:
      - "com.demo.app=ai-ready-demo"
      - "com.demo.component=frontend"
      - "com.demo.managed-by=start-script"

  # Lightweight SQLite container for data browsing (optional)
  db:
    image: keinos/sqlite3:latest
    volumes:
      - sqlite-data:/data
    command: sh -c "while true; do sleep 3600; done" # Keep container running
    labels:
      - "com.demo.app=ai-ready-demo"
      - "com.demo.component=database"
      - "com.demo.managed-by=start-script"

volumes:
  sqlite-data: # For SQLite database file
  frontend-node-modules:
