services:
  backend:
    build:
      context: ../backend
      target: development
    volumes:
      - ../backend:/app
      - postgres-data:/app/data
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_db
    command: >
      bash -c "
        mkdir -p /app/data &&
        chown -R vscode:vscode /app/data &&
        chmod 777 /app/data &&
        cd /app &&
        tail -f /dev/null
      "
    tty: true
    stdin_open: true
    labels:
      - "com.app=dev-container"
      - "com.component=backend"
      - "com.managed-by=start-script"

  frontend:
    build:
      context: ../frontend
      target: development
    volumes:
      - ../frontend:/app
      - frontend-node-modules:/app/node_modules
    ports:
      - "3001:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8001
    command: npm run dev -- --host 0.0.0.0
    labels:
      - "com.app=dev-container"
      - "com.component=frontend"
      - "com.managed-by=start-script"

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    labels:
      - "com.app=dev-container"
      - "com.component=database"
      - "com.managed-by=start-script"

volumes:
  postgres-data:
  frontend-node-modules:
